name: frogedu-microservices all

services:
  frog-user-db:
    image: postgres:17-alpine
    container_name: frog-user-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - frog_user_db_data:/var/lib/postgresql/data
    networks:
      - frogedu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d user"]
      interval: 10s
      timeout: 5s
      retries: 5

  frog-exam-db:
    image: postgres:17-alpine
    container_name: frog-exam-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: exam
    ports:
      - "5433:5432"
    volumes:
      - frog_exam_db_data:/var/lib/postgresql/data
    networks:
      - frogedu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d exam"]
      interval: 10s
      timeout: 5s
      retries: 5

  frog-class-db:
    image: postgres:17-alpine
    container_name: frog-class-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: class
    ports:
      - "5434:5432"
    volumes:
      - frog_class_db_data:/var/lib/postgresql/data
    networks:
      - frogedu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d class"]
      interval: 10s
      timeout: 5s
      retries: 5

  frog-subscription-db:
    image: postgres:17-alpine
    container_name: frog-subscription-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: subscription
    ports:
      - "5435:5432"
    volumes:
      - frog_subscription_db_data:/var/lib/postgresql/data
    networks:
      - frogedu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d subscription"]
      interval: 10s
      timeout: 5s
      retries: 5

  frog-storage:
    image: minio/minio:latest
    container_name: frog-storage
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - frog_storage_data:/data
    networks:
      - frogedu-network
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Microservices
  frog-user-service:
    build:
      context: .
      dockerfile: Services/User/Dockerfile
    container_name: frog-user-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      USER_DB_CONNECTION_STRING: "postgresql://root:root@frog-user-db:5432/user?sslmode=disable"
    ports:
      - "8000:8080"
    networks:
      - frogedu-network
    depends_on:
      frog-user-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frog-exam-service:
    build:
      context: .
      dockerfile: Services/Exam/Dockerfile
    container_name: frog-exam-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      EXAM_DB_CONNECTION_STRING: "postgresql://root:root@frog-exam-db:5433/exam?sslmode=disable"
    ports:
      - "8001:8080"
    networks:
      - frogedu-network
    depends_on:
      frog-exam-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frog-class-service:
    build:
      context: .
      dockerfile: Services/Class/Dockerfile
    container_name: frog-class-service

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      CLASS_DB_CONNECTION_STRING: "postgresql://root:root@frog-class-db:5434/class?sslmode=disable"
    ports:
      - "8002:8080"
    networks:
      - frogedu-network
    depends_on:
      frog-class-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frog-subscription-service:
    build:
      context: .
      dockerfile: Services/AI/Dockerfile
    container_name: frog-subscription-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SUBSCRIPTION_DB_CONNECTION_STRING: "postgresql://root:root@frog-subscription-db:5435/subscription?sslmode=disable"
    ports:
      - "8003:8080"
    networks:
      - frogedu-network
    depends_on:
      frog-subscription-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frog-api-gateway:
    image: nginx:alpine
    container_name: frog-api-gateway
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frogedu-network
    depends_on:
      - frog-user-service
      - frog-exam-service
      - frog-class-service
      - frog-subscription-service
      - frog-storage
    environment:
      - USER_SERVICE_URL=http://frog-user-service:8080
      - EXAM_SERVICE_URL=http://frog-exam-service:8080
      - CLASS_SERVICE_URL=http://frog-class-service:8080
      - SUBSCRIPTION_SERVICE_URL=http://frog-subscription-service:8080
      - STORAGE_SERVICE_URL=http://frog-storage:9000
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  frogedu-network:

volumes:
  frog_user_db_data:
  frog_exam_db_data:
  frog_class_db_data:
  frog_subscription_db_data:
  frog_storage_data:
