name: assessment-cd

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "backend/Services/Assessment/**.cs"
      - "backend/Shared/**.cs"
      - ".github/workflows/assessment-cd.yaml"
      - "backend/Services/Assessment/**.csproj"
      - "backend/Shared/**.csproj"
  workflow_dispatch:

jobs:
  assessment-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            backend/Shared
            backend/Services/Assessment

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        working-directory: backend/
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: frogedu-dev-assessment-api
        run: |
          docker build --provenance=false -f Services/Assessment/Dockerfile -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Update Lambda Function
        env:
          FUNCTION_NAME: frogedu-assessments
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: frogedu-dev-assessment-api
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --image-uri $REGISTRY/$REPOSITORY:latest
